version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sreality
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adam -d sreality"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
  
  scraper:
    build: ./sreality-scraper
    volumes:
      - ./sreality-scraper:/usr/src/sreality-scraper
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  server:
    build: ./sreality-server
    ports:
      - 8080:8080
    depends_on:
      - scraper
    networks:
      - mynetwork  

networks:
  mynetwork:

volumes:
  postgres_data: